name: my-search-engine-demo
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=20.2.1
  - python=3.8.5
  - requests=2.24.0
  - setuptools=49.2.1
  
  - pip:
    - azure-search-documents==11.0.0
    - streamlit==0.64.0

